export const STATE_OPTIONS = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de Mexico",
  "Coahuila",
  "Colima",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Mexico",
  "Michoacan",
  "Morelos",
  "Nayarit",
  "Nuevo Leon",
  "Oaxaca",
  "Puebla",
  "Queretaro",
  "Quintana Roo",
  "San Luis Potosi",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatan",
  "Zacatecas",
];

export const GENDER_OPTIONS = ["Femenino", "Masculino", "No binario", "Prefiero no decir"];

export const AGE_OPTIONS = Array.from({ length: 100 }, (_, index) => String(index + 1));

export const MUNICIPALITIES_BY_STATE = {
  "Aguascalientes": ["Aguascalientes", "Asientos", "Calvillo", "Jesus Maria", "Pabellon de Arteaga", "Rincon de Romos", "Otro municipio"],
  "Baja California": ["Mexicali", "Tijuana", "Ensenada", "Tecate", "Playas de Rosarito", "San Quintin", "Otro municipio"],
  "Baja California Sur": ["La Paz", "Los Cabos", "Comondu", "Loreto", "Mulege", "Otro municipio"],
  "Campeche": ["Campeche", "Carmen", "Champoton", "Escarcega", "Hecelchakan", "Otro municipio"],
  "Chiapas": ["Tuxtla Gutierrez", "Tapachula", "San Cristobal de las Casas", "Comitan de Dominguez", "Palenque", "Tonala", "Otro municipio"],
  "Chihuahua": ["Chihuahua", "Juarez", "Delicias", "Cuauhtemoc", "Hidalgo del Parral", "Nuevo Casas Grandes", "Otro municipio"],
  "Ciudad de Mexico": ["Alvaro Obregon", "Azcapotzalco", "Benito Juarez", "Coyoacan", "Cuajimalpa de Morelos", "Cuauhtemoc", "Gustavo A. Madero", "Iztacalco", "Iztapalapa", "Miguel Hidalgo", "Tlalpan", "Xochimilco", "Otro municipio"],
  "Coahuila": ["Saltillo", "Torreon", "Monclova", "Piedras Negras", "Acuna", "Ramos Arizpe", "Otro municipio"],
  "Colima": ["Colima", "Manzanillo", "Villa de Alvarez", "Tecoman", "Armeria", "Otro municipio"],
  "Durango": ["Durango", "Gomez Palacio", "Lerdo", "Pueblo Nuevo", "Santiago Papasquiaro", "Otro municipio"],
  "Guanajuato": ["Leon", "Irapuato", "Celaya", "Salamanca", "San Miguel de Allende", "Guanajuato", "Otro municipio"],
  "Guerrero": ["Acapulco de Juarez", "Chilpancingo de los Bravo", "Iguala de la Independencia", "Taxco de Alarcon", "Zihuatanejo de Azueta", "Otro municipio"],
  "Hidalgo": ["Pachuca de Soto", "Tulancingo de Bravo", "Tula de Allende", "Huejutla de Reyes", "Mineral de la Reforma", "Actopan", "Otro municipio"],
  "Jalisco": ["Guadalajara", "Zapopan", "San Pedro Tlaquepaque", "Tonala", "Puerto Vallarta", "Tlajomulco de Zuniga", "Lagos de Moreno", "Otro municipio"],
  "Mexico": ["Toluca", "Ecatepec de Morelos", "Nezahualcoyotl", "Naucalpan de Juarez", "Tlalnepantla de Baz", "Chimalhuacan", "Cuautitlan Izcalli", "Atizapan de Zaragoza", "Otro municipio"],
  "Michoacan": ["Morelia", "Uruapan", "Zamora", "Lazaro Cardenas", "Apatzingan", "Zitacuaro", "Otro municipio"],
  "Morelos": ["Cuernavaca", "Jiutepec", "Cuautla", "Temixco", "Yautepec", "Jojutla", "Otro municipio"],
  "Nayarit": ["Tepic", "Bahia de Banderas", "Santiago Ixcuintla", "Compostela", "Xalisco", "Otro municipio"],
  "Nuevo Leon": ["Monterrey", "Guadalupe", "San Nicolas de los Garza", "Apodaca", "Santa Catarina", "San Pedro Garza Garcia", "General Escobedo", "Otro municipio"],
  "Oaxaca": ["Oaxaca de Juarez", "San Juan Bautista Tuxtepec", "Juchitan de Zaragoza", "Salina Cruz", "Huajuapan de Leon", "Santa Maria Huatulco", "Otro municipio"],
  "Puebla": ["Puebla", "Tehuacan", "San Martin Texmelucan", "Atlixco", "San Pedro Cholula", "Teziutlan", "Huauchinango", "Otro municipio"],
  "Queretaro": ["Queretaro", "San Juan del Rio", "Corregidora", "El Marques", "Tequisquiapan", "Cadereyta de Montes", "Otro municipio"],
  "Quintana Roo": ["Benito Juarez", "Solidaridad", "Othon P. Blanco", "Cozumel", "Tulum", "Isla Mujeres", "Otro municipio"],
  "San Luis Potosi": ["San Luis Potosi", "Soledad de Graciano Sanchez", "Ciudad Valles", "Matehuala", "Rioverde", "Tamazunchale", "Otro municipio"],
  "Sinaloa": ["Culiacan", "Mazatlan", "Ahome", "Guasave", "Navolato", "Salvador Alvarado", "Otro municipio"],
  "Sonora": ["Hermosillo", "Cajeme", "Nogales", "San Luis Rio Colorado", "Guaymas", "Navojoa", "Otro municipio"],
  "Tabasco": ["Centro", "Cardenas", "Comalcalco", "Huimanguillo", "Macuspana", "Paraiso", "Otro municipio"],
  "Tamaulipas": ["Reynosa", "Matamoros", "Nuevo Laredo", "Victoria", "Tampico", "Altamira", "Ciudad Madero", "Otro municipio"],
  "Tlaxcala": ["Tlaxcala", "Apizaco", "Huamantla", "Chiautempan", "Tlaxco", "Zacatelco", "Otro municipio"],
  "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Poza Rica de Hidalgo", "Cordoba", "Orizaba", "Boca del Rio", "Minatitlan", "Otro municipio"],
  "Yucatan": ["Merida", "Valladolid", "Tizimin", "Progreso", "Uman", "Kanasin", "Otro municipio"],
  "Zacatecas": ["Zacatecas", "Guadalupe", "Fresnillo", "Jerez", "Rio Grande", "Sombrerete", "Otro municipio"],
};

export function getMunicipalityOptions(state) {
  return MUNICIPALITIES_BY_STATE[state] || [];
}