export const RESPONDER_UI = {
  policia: {
    variant: "policia",
    headerTitle: "Panel de Policia",
    roleCaption: "Unidad activa",
    brandIcon: "shield-outline",
    profileIcon: "shield-outline",
    brandColor: "#1D4ED8",
    accentColor: "#1D4ED8",
    dangerColor: "#DC2626",
    badgeColor: "#16A34A",
    profileScreen: "PoliceProfile",
    detailScreen: "PoliceAlert",
    historyScreen: "PoliceHistory",
    notificationsScreen: "PoliceNotifications",
    menuTitle: "Menu policia",
    alertCardTitle: "Emergencia policial",
    emptyText: "Sin alertas por ahora. Cuando entre una en tu zona o te la asignen, te aparecera aqui.",
    defaultUnitLabel: "Patrulla",
    notificationTitleNearby: "Nueva alerta en tu zona",
    notificationTitleAssigned: "Alerta asignada",
    sectionTitle: "Emergencias policiales pendientes",
    historyTitle: "Historial de atenciones",
    instructions: [
      "Mantente en estado disponible cuando estes en servicio.",
      "Confirma y atiende alertas dentro del SLA institucional.",
      "Actualiza el estado al llegar al incidente.",
      "Cierra la alerta con reporte completo al finalizar.",
    ],
    filterAlert: (item) => (item?.tipo || "").toLowerCase() !== "medica",
  },
  ambulancia: {
    variant: "ambulancia",
    headerTitle: "Panel de Ambulancia",
    roleCaption: "Unidad activa",
    brandIcon: "heart-outline",
    profileIcon: "heart-outline",
    brandColor: "#DC2626",
    accentColor: "#EA580C",
    dangerColor: "#DC2626",
    badgeColor: "#EF4444",
    profileScreen: "AmbulanceProfile",
    detailScreen: "AmbulanceAlert",
    historyScreen: "AmbulanceHistory",
    notificationsScreen: "AmbulanceNotifications",
    menuTitle: "Menu ambulancia",
    alertCardTitle: "Emergencia medica",
    emptyText: "Sin alertas por ahora. Cuando entre una en tu zona o te la asignen, te aparecera aqui.",
    defaultUnitLabel: "Ambulancia",
    notificationTitleNearby: "Nueva emergencia medica cercana",
    notificationTitleAssigned: "Emergencia asignada",
    sectionTitle: "Emergencias medicas pendientes",
    historyTitle: "Historial de servicios",
    instructions: [
      "Mantente en estado disponible durante tu guardia activa.",
      "Responde alertas medicas dentro del SLA institucional.",
      "Actualiza el estado al llegar con el paciente.",
      "Cierra la alerta con reporte clinico al finalizar.",
    ],
    filterAlert: (item) => (item?.tipo || "").toLowerCase() === "medica",
  },
};

export function getResponderUi(variant) {
  return RESPONDER_UI[variant] || RESPONDER_UI.policia;
}